---
- name: "s3_exporter | Install the required packages in Redhat derivatives"
  ansible.builtin.dnf:
    name: "{{ s3_exporter_pacakges_variant }}"
    state: "{{ vars['s3_exporter_package_state'] | default(omit) }}"
    update_cache: "yes"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'RedHat'"
- name: "s3_exporter | Install the required packages in Debian derivatives"
  ansible.builtin.apt:
    name: "{{ s3_exporter_pacakges_variant }}"
    state: "{{ vars['s3_exporter_package_state'] | default(omit) }}"
    update_cache: "yes"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'Debian'"
- name: "s3_exporter | Install the required packages in ArchLinux derivatives"
  community.general.pacman:
    name: "{{ s3_exporter_pacakges_variant }}"
    state: "{{ vars['s3_exporter_package_state'] | default(omit) }}"
    update_cache: "yes"
  when:
    - "hostvars[inventory_hostname]['ansible_os_family'] == 'Archlinux'"
